
'------------------------------------------------------------------------------
' 
'     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
'     Created at 23/07/2011
'     Created from Windows
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' 
'------------------------------------------------------------------------------
Imports System
Imports System.Text
Imports System.Collections
Imports System.Runtime.InteropServices
Imports System.Xml.Serialization
Imports System.Web.Services
Imports System.Web.Services.Description
Imports System.Web.Services.Protocols
Imports SAP.Connector



  '@ <summary>
  '@ A typed collection of DDFIXVALUE elements.
  '@ </summary>
  <Serializable> _
  Public Class DDFIXVALUES 
    Inherits SAPTable 
  
    '@ <summary>
    '@ Returns the element type DDFIXVALUE.
    '@ </summary>
    '@ <returns>The type DDFIXVALUE.</returns>
    Public Overloads Overrides Function GetElementType() As Type
        Return GetType(DDFIXVALUE)
    End Function

    '@ <summary>
    '@ Creates an empty new row of type DDFIXVALUE.
    '@ </summary>
    '@ <returns>The newDDFIXVALUE.</returns>
    Overrides Public Function CreateNewRow() As Object 
        Return new DDFIXVALUE()
    End Function
     
    '@ <summary>
    '@ The indexer of the collection.
    '@ </summary>
    Default Public Property Item(ByVal Index As Integer) As DDFIXVALUE 
        Get 
            Return CType(List(Index), DDFIXVALUE)
        End Get
        Set(ByVal Value As DDFIXVALUE)
            List(Index) = Value
        End Set
    End Property
        
    '@ <summary>
    '@ Adds a DDFIXVALUE to the end of the collection.
    '@ </summary>
    '@ <param name="value">The DDFIXVALUE to be added to the end of the collection.</param>
    '@ <returns>The index of the newDDFIXVALUE.</returns>
    Public Function Add(ByVal Value As DDFIXVALUE) As Integer 
        Return List.Add(Value)
    End Function
        
    '@ <summary>
    '@ Inserts a DDFIXVALUE into the collection at the specified index.
    '@ </summary>
    '@ <param name="index">The zero-based index at which value should be inserted.</param>
    '@ <param name="value">The DDFIXVALUE to insert.</param>
    Public Sub Insert(ByVal Index As Integer, ByVal Value As DDFIXVALUE) 
        List.Insert(Index, value)
    End Sub
        
    '@ <summary>
    '@ Searches for the specified DDFIXVALUE and returnes the zero-based index of the first occurrence in the collection.
    '@ </summary>
    '@ <param name="value">The DDFIXVALUE to locate in the collection.</param>
    '@ <returns>The index of the object found or -1.</returns>
    Public Function IndexOf(ByVal Value As DDFIXVALUE) As Integer
        Return List.IndexOf(value)
    End Function
        
    '@ <summary>
    '@ Determines wheter an element is in the collection.
    '@ </summary>
    '@ <param name="value">The DDFIXVALUE to locate in the collection.</param>
    '@ <returns>True if found; else false.</returns>
    Public Function Contains(ByVal Value As DDFIXVALUE) As Boolean
        Return List.Contains(value)
    End Function
        
    '@ <summary>
    '@ Removes the first occurrence of the specified DDFIXVALUE from the collection.
    '@ </summary>
    '@ <param name="value">The DDFIXVALUE to remove from the collection.</param>
    Public Sub Remove(ByVal Value As DDFIXVALUE) 
        List.Remove(value)
    End Sub

    '@ <summary>
    '@ Copies the contents of the DDFIXVALUES to the specified one-dimensional array starting at the specified index in the target array.
    '@ </summary>
    '@ <param name="array">The one-dimensional destination array.</param>           
    '@ <param name="index">The zero-based index in array at which copying begins.</param>           
    Public Sub CopyTo(ByVal Array() As DDFIXVALUE, ByVal Index As Integer) 
        List.CopyTo(array, index)
    End Sub
  End Class
