
'------------------------------------------------------------------------------
' 
'     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
'     Created at 23/07/2011
'     Created from Windows
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' 
'------------------------------------------------------------------------------
Imports System
Imports System.Text
Imports System.Collections
Imports System.Runtime.InteropServices
Imports System.Xml.Serialization
Imports System.Web.Services
Imports System.Web.Services.Description
Imports System.Web.Services.Protocols
Imports SAP.Connector



  '@ <summary>
  '@ A typed collection of DFIES elements.
  '@ </summary>
  <Serializable> _
  Public Class DDFIELDS 
    Inherits SAPTable 
  
    '@ <summary>
    '@ Returns the element type DFIES.
    '@ </summary>
    '@ <returns>The type DFIES.</returns>
    Public Overloads Overrides Function GetElementType() As Type
        Return GetType(DFIES)
    End Function

    '@ <summary>
    '@ Creates an empty new row of type DFIES.
    '@ </summary>
    '@ <returns>The newDFIES.</returns>
    Overrides Public Function CreateNewRow() As Object 
        Return new DFIES()
    End Function
     
    '@ <summary>
    '@ The indexer of the collection.
    '@ </summary>
    Default Public Property Item(ByVal Index As Integer) As DFIES 
        Get 
            Return CType(List(Index), DFIES)
        End Get
        Set(ByVal Value As DFIES)
            List(Index) = Value
        End Set
    End Property
        
    '@ <summary>
    '@ Adds a DFIES to the end of the collection.
    '@ </summary>
    '@ <param name="value">The DFIES to be added to the end of the collection.</param>
    '@ <returns>The index of the newDFIES.</returns>
    Public Function Add(ByVal Value As DFIES) As Integer 
        Return List.Add(Value)
    End Function
        
    '@ <summary>
    '@ Inserts a DFIES into the collection at the specified index.
    '@ </summary>
    '@ <param name="index">The zero-based index at which value should be inserted.</param>
    '@ <param name="value">The DFIES to insert.</param>
    Public Sub Insert(ByVal Index As Integer, ByVal Value As DFIES) 
        List.Insert(Index, value)
    End Sub
        
    '@ <summary>
    '@ Searches for the specified DFIES and returnes the zero-based index of the first occurrence in the collection.
    '@ </summary>
    '@ <param name="value">The DFIES to locate in the collection.</param>
    '@ <returns>The index of the object found or -1.</returns>
    Public Function IndexOf(ByVal Value As DFIES) As Integer
        Return List.IndexOf(value)
    End Function
        
    '@ <summary>
    '@ Determines wheter an element is in the collection.
    '@ </summary>
    '@ <param name="value">The DFIES to locate in the collection.</param>
    '@ <returns>True if found; else false.</returns>
    Public Function Contains(ByVal Value As DFIES) As Boolean
        Return List.Contains(value)
    End Function
        
    '@ <summary>
    '@ Removes the first occurrence of the specified DFIES from the collection.
    '@ </summary>
    '@ <param name="value">The DFIES to remove from the collection.</param>
    Public Sub Remove(ByVal Value As DFIES) 
        List.Remove(value)
    End Sub

    '@ <summary>
    '@ Copies the contents of the DDFIELDS to the specified one-dimensional array starting at the specified index in the target array.
    '@ </summary>
    '@ <param name="array">The one-dimensional destination array.</param>           
    '@ <param name="index">The zero-based index in array at which copying begins.</param>           
    Public Sub CopyTo(ByVal Array() As DFIES, ByVal Index As Integer) 
        List.CopyTo(array, index)
    End Sub
  End Class
